const data=[
{slug:'rebuild',no:'01',title:'REBUILD',type:'VISUAL RESEARCH',year:'2024',cover:'assets/rebuild-poster.webp',bg:'assets/rebuild-collapse.webp',pages:['assets/rebuild-poster.webp','assets/rebuild-collapse.webp','assets/rebuild-structure.webp','assets/rebuild-construction.webp'],desc:'A visual investigation into unfinished architecture, urban memory and reconstruction.',role:'Concept, Photography, Art Direction, Editorial Design',tools:'Photoshop, Lightroom'},
{slug:'yunnan-fungal-diversity',no:'02',title:'YUNNAN FUNGAL DIVERSITY',type:'FIELD EDITORIAL',year:'2025',cover:'assets/fungi-cover.webp',bg:'assets/golden-ear.webp',pages:['assets/fungi-cover.webp','assets/golden-ear.webp','assets/gongshan-mist.webp','assets/gongshan-portrait.webp','assets/gongshan-rock.webp'],desc:'An editorial study of fungal diversity, landscape and field observation in Yunnan.',role:'Research, Photography, Editorial Design',tools:'Photoshop, InDesign'},
{slug:'the-breath-of-indigo',no:'03',title:'THE BREATH OF INDIGO',type:'INTERACTIVE EXPERIENCE',year:'2026',cover:'assets/indigo-hero.webp',bg:'assets/indigo-craft.webp',pages:['assets/indigo-hero.webp','assets/indigo-craft.webp','assets/indigo-workshop.webp'],desc:'A digital experience shaped by indigo dye, material rhythm and traditional craft.',role:'Concept, UI Design, Interaction Design',tools:'Figma, Web Development'},
{slug:'shape-of-love',no:'04',title:'SHAPE OF LOVE',type:'PERSONAL EDITORIAL',year:'2025',cover:'assets/love-birthday.webp',bg:'assets/love-portrait-2.webp',pages:['assets/love-birthday.webp','assets/love-portrait-1.webp','assets/love-portrait-2.webp','assets/love-portrait-3.webp','assets/love-throw.webp'],desc:'A personal birthday editorial about affection, memory and the image of growing up.',role:'Photography, Styling, Editorial Design',tools:'Photoshop, Lightroom'}];
const $=s=>document.querySelector(s),ambient=$('.ambient');let active=-1,page=0,busy=false;
function mood(p){ambient.style.backgroundImage=`url('${p.bg}')`;ambient.style.backgroundColor=p.slug.includes('indigo')?'#102b43':p.slug.includes('fungal')?'#6b5429':p.slug.includes('love')?'#75545b':'#303030'}
data.forEach((p,i)=>{let b=document.createElement('button');b.className='card';b.innerHTML=`<div class="poster"><img src="${p.cover}" alt="${p.title} poster"></div><div class="meta"><span>${p.no}</span><div><strong>${p.title}</strong><small>${p.type} · ${p.year}</small></div></div>`;b.onmouseenter=b.onfocus=()=>mood(p);b.onclick=()=>openProject(i);$('#projects').append(b);let x=document.createElement('button');x.className='indexItem';x.innerHTML=`<img src="${p.cover}" alt=""><span>${p.no} — ${p.title}</span>`;x.onclick=()=>{$('#index').classList.remove('active');openProject(i)};$('#indexGrid').append(x)});mood(data[0]);
function pair(){let p=data[active],mobile=innerWidth<=800;if(!page)return[null,p.pages[0]];return mobile?[null,p.pages[page]]:[p.pages[page]||null,p.pages[page+1]||null]}
function draw(){let p=data[active],[l,r]=pair(),book=$('#book');book.className=page?'open':'';book.innerHTML=`<div class="page left ${l?'':'blank'}">${l?`<img src="${l}" alt="${p.title} page">`:''}</div><div class="page right ${r?'':'blank'}">${r?`<img src="${r}" alt="${p.title} page">`:''}</div>`;$('#count').textContent=page?`${String(page+1).padStart(2,'0')} / ${String(p.pages.length).padStart(2,'0')}`:'COVER'}
function openProject(i){active=i;page=0;let p=data[i];mood(p);location.hash=p.slug;$('#home').style.cssText='opacity:0;transform:scale(.985)';$('#viewer').classList.add('active');$('#closeBtn').style.display='block';$('#status').innerHTML=`<span>${p.no} / 04</span><span>${p.title}</span>`;$('.viewerBg').style.backgroundImage=`url('${p.bg}')`;$('#info').innerHTML=`<h2>${p.title}</h2><dl><dt>YEAR</dt><dd>${p.year}</dd><dt>TYPE</dt><dd>${p.type}</dd><dt>ROLE</dt><dd>${p.role}</dd><dt>TOOLS</dt><dd>${p.tools}</dd></dl><p>${p.desc}</p>`;draw()}
function turn(dir){if(active<0||busy)return;let step=innerWidth<=800?1:2,max=data[active].pages.length-1,next=Math.max(0,Math.min(max,page+(dir==='next'?step:-step)));if(next===page){if(dir==='next'&&active<data.length-1)openProject(active+1);return}let old=$('#book').querySelector(dir==='next'?'.right':'.left'),leaf=old&&old.cloneNode(true);page=next;draw();if(leaf){busy=true;leaf.classList.add('turn');if(dir!=='next')leaf.classList.add('back');$('#book').append(leaf);setTimeout(()=>{leaf.remove();busy=false},880)}}
function close(){active=-1;location.hash='home';$('#viewer').classList.remove('active');$('#info').classList.remove('active');$('#home').style.cssText='';$('#closeBtn').style.display='none';$('#status').innerHTML='<span>SELECTED WORKS</span><span>2024—2026</span>'}
$('.next').onclick=$('#nextBtn').onclick=()=>turn('next');$('.prev').onclick=$('#prevBtn').onclick=()=>turn('previous');$('#closeBtn').onclick=close;$('#infoBtn').onclick=()=>active>=0&&$('#info').classList.toggle('active');$('#indexBtn').onclick=()=>$('#index').classList.add('active');$('#indexClose').onclick=()=>$('#index').classList.remove('active');
addEventListener('keydown',e=>{if(e.key==='ArrowRight')turn('next');if(e.key==='ArrowLeft')turn('previous');if(e.key==='Escape')close()});let tx=0;$('#viewer').ontouchstart=e=>tx=e.changedTouches[0].clientX;$('#viewer').ontouchend=e=>{let d=e.changedTouches[0].clientX-tx;if(Math.abs(d)>45)turn(d<0?'next':'previous')};let initial=data.findIndex(p=>p.slug===location.hash.slice(1));if(initial>=0)openProject(initial);
