document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="vertical.css?v=6"><link rel="stylesheet" href="corrections.css?v=6"><link rel="stylesheet" href="image-fix.css?v=6"><link rel="stylesheet" href="book-restore.css?v=6"><link rel="stylesheet" href="motion-v6.css?v=6">');
const data=[
{slug:'rebuild',no:'01',title:'REBUILD',type:'VISUAL RESEARCH',year:'2024',cover:'assets/rebuild-poster.webp',bg:'assets/rebuild-collapse.webp',pages:['assets/rebuild-poster.webp','assets/rebuild-collapse.webp','assets/rebuild-structure.webp','assets/rebuild-construction.webp'],desc:'A visual investigation into unfinished architecture, urban memory and reconstruction.',role:'Concept, Photography, Art Direction, Editorial Design',tools:'Photoshop, Lightroom'},
{slug:'yunnan-fungal-diversity',no:'02',title:'YUNNAN FUNGAL DIVERSITY',type:'FIELD EDITORIAL',year:'2025',cover:'assets/fungi-cover.webp',bg:'assets/golden-ear.webp',pages:['assets/fungi-cover.webp','assets/golden-ear.webp','assets/gongshan-mist.webp','assets/gongshan-portrait.webp','assets/gongshan-rock.webp'],desc:'An editorial study of fungal diversity, landscape and field observation in Yunnan.',role:'Research, Photography, Editorial Design',tools:'Photoshop, InDesign'},
{slug:'the-breath-of-indigo',no:'03',title:'THE BREATH OF INDIGO',type:'INTERACTIVE EXPERIENCE',year:'2026',cover:'assets/indigo-hero.webp',bg:'assets/indigo-craft.webp',pages:['assets/indigo-hero.webp','assets/indigo-craft.webp','assets/indigo-workshop.webp'],desc:'A digital experience shaped by indigo dye, material rhythm and traditional craft.',role:'Concept, UI Design, Interaction Design',tools:'Figma, Web Development'},
{slug:'shape-of-love',no:'04',title:'SHAPE OF LOVE',type:'PERSONAL EDITORIAL',year:'2025',cover:'assets/love-birthday.webp',bg:'assets/love-portrait-2.webp',pages:['assets/love-birthday.webp','assets/love-portrait-1.webp','assets/love-portrait-2.webp','assets/love-portrait-3.webp','assets/love-throw.webp'],desc:'A personal birthday editorial about affection, memory and the image of growing up.',role:'Photography, Styling, Editorial Design',tools:'Photoshop, Lightroom'}];
const $=s=>document.querySelector(s),ambient=$('.ambient');let active=-1,page=0,busy=false;
function mood(p){ambient.style.backgroundImage=`url('${p.bg}')`;ambient.style.backgroundColor=p.slug.includes('indigo')?'#102b43':p.slug.includes('fungal')?'#6b5429':p.slug.includes('love')?'#75545b':'#303030'}
data.forEach((p,i)=>{let b=document.createElement('button');b.className='card';b.innerHTML=`<div class="poster" style="--image:url('${p.cover}')"><img src="${p.cover}" alt="${p.title} poster"></div><div class="projectCopy"><div class="meta"><span>${p.no}</span><div><strong>${p.title}</strong><small>${p.type} · ${p.year}</small></div></div><p>${p.desc}</p><span class="viewProject">VIEW PROJECT&nbsp;&nbsp;↗</span></div>`;b.onmouseenter=b.onfocus=()=>mood(p);b.onclick=()=>openProject(i);$('#projects').append(b);let x=document.createElement('button');x.className='indexItem';x.innerHTML=`<img src="${p.cover}" alt=""><span>${p.no} — ${p.title}</span>`;x.onclick=()=>{$('#index').classList.remove('active');openProject(i)};$('#indexGrid').append(x)});mood(data[0]);
function pair(){let p=data[active],mobile=innerWidth<=800;if(!page)return[null,p.pages[0]];return mobile?[null,p.pages[page%p.pages.length]]:[p.pages[page%p.pages.length],p.pages[(page+1)%p.pages.length]]}
function imagePage(side,src,p){return `<div class="page ${side}" style="--image:url('${src}')"><img src="${src}" alt="${p.title} page"></div>`}
function draw(){let p=data[active];if(active===2){drawWeb();return}let [l,r]=pair(),book=$('#book');book.className=page?'open':'';book.innerHTML=`${l?imagePage('left',l,p):''}${imagePage('right',r,p)}`;$('#count').textContent=page?`${String(page+1).padStart(2,'0')} / ${String(p.pages.length).padStart(2,'0')}`:'COVER'}
function drawWeb(){let p=data[active],labels=['OVERVIEW','EXPERIENCE','INTERACTION'],src=p.pages[page%p.pages.length];$('#book').className='webCanvas';$('#book').innerHTML=`<div class="browserBar"><i></i><i></i><i></i><span>the-breath-of-indigo</span></div><div class="webImage" style="--image:url('${src}')"><img src="${src}" alt="${labels[page]}"></div><div class="webTabs">${labels.map((x,i)=>`<button class="${i===page?'active':''}" data-tab="${i}">${x}</button>`).join('')}<button data-tab="0">LIVE SITE ↗</button></div>`;$('#book').querySelectorAll('[data-tab]').forEach(x=>x.onclick=e=>{e.stopPropagation();page=+x.dataset.tab;drawWeb()});$('#count').textContent=labels[page]}
function openProject(i){active=i;page=0;let p=data[i];mood(p);location.hash=p.slug;$('#home').style.cssText='opacity:0;transform:scale(.985)';$('#viewer').classList.add('active');$('#viewer').classList.toggle('webMode',i===2);$('#closeBtn').style.display='block';$('#status').innerHTML=`<span>${p.no} / 04</span><span>${p.title}</span>`;$('.viewerBg').style.backgroundImage=`url('${p.bg}')`;$('#info').innerHTML=`<h2>${p.title}</h2><dl><dt>YEAR</dt><dd>${p.year}</dd><dt>TYPE</dt><dd>${p.type}</dd><dt>ROLE</dt><dd>${p.role}</dd><dt>TOOLS</dt><dd>${p.tools}</dd></dl><p>${p.desc}</p>`;draw()}
function turn(dir){if(active<0||busy)return;let p=data[active],len=p.pages.length;if(active===2){page=(page+(dir==='next'?1:-1)+len)%len;drawWeb();return}let next;if(dir==='next')next=page===0?1:(page+(innerWidth<=800?1:2))%len;else next=page===0?(innerWidth<=800?len-1:(len%2?len-2:len-1)):Math.max(0,page-(innerWidth<=800?1:2));let old=$('#book').querySelector(dir==='next'?'.right':'.left'),leaf=old&&old.cloneNode(true);page=next;draw();if(leaf){busy=true;leaf.classList.add('turn');if(dir!=='next')leaf.classList.add('back');$('#book').append(leaf);setTimeout(()=>{leaf.remove();busy=false},880)}}
function close(){active=-1;location.hash='home';$('#viewer').classList.remove('active');$('#info').classList.remove('active');$('#home').style.cssText='';$('#closeBtn').style.display='none';$('#status').innerHTML='<span>SELECTED WORKS</span><span>2024—2026</span>'}
$('.next').onclick=$('#nextBtn').onclick=()=>turn('next');$('.prev').onclick=$('#prevBtn').onclick=()=>turn('previous');$('#closeBtn').onclick=close;$('#infoBtn').onclick=()=>active>=0&&$('#info').classList.toggle('active');$('#indexBtn').onclick=()=>$('#index').classList.add('active');$('#indexClose').onclick=()=>$('#index').classList.remove('active');
addEventListener('keydown',e=>{if(e.key==='ArrowRight')turn('next');if(e.key==='ArrowLeft')turn('previous');if(e.key==='Escape')close()});let tx=0;$('#viewer').ontouchstart=e=>tx=e.changedTouches[0].clientX;$('#viewer').ontouchend=e=>{let d=e.changedTouches[0].clientX-tx;if(Math.abs(d)>45)turn(d<0?'next':'previous')};let initial=data.findIndex(p=>p.slug===location.hash.slice(1));

/* V6 — unified reading-room motion system */
let sourcePoster=null,transitionState='closed';
function endPage(side,p){return `<div class="page ${side} endPage"><div><span>${p.no} / 04</span><h3>${p.title}</h3><p>${p.desc}</p><small>END OF EDITION</small></div></div>`}
function pair(){let p=data[active],mobile=innerWidth<=800;if(!page)return[null,p.pages[0]];if(mobile)return[null,p.pages[page]];return[p.pages[page],p.pages[page+1]||'END']}
function draw(){let p=data[active];if(active===2){drawWeb();return}let [l,r]=pair(),book=$('#book');book.dataset.kind=p.slug;book.className=page?'open':'';book.innerHTML=`${l?imagePage('left',l,p):''}${r==='END'?endPage('right',p):imagePage('right',r,p)}`;$('#count').textContent=page?`${String(page+1).padStart(2,'0')} / ${String(p.pages.length).padStart(2,'0')}`:'COVER'}
function targetBox(web){if(web){let w=Math.min(innerWidth*.82,1180),h=Math.min(innerHeight*.76,760);return{left:(innerWidth-w)/2,top:(innerHeight-h)/2,width:w,height:h}}let h=Math.min(innerHeight*.76,760),w=h*297/420;return{left:(innerWidth-w)/2,top:(innerHeight-h)/2,width:w,height:h}}
function flyPoster(poster,i,opening,done){if(!poster||matchMedia('(prefers-reduced-motion: reduce)').matches){done();return}let from=poster.getBoundingClientRect(),to=targetBox(i===2),box=opening?from:to,dest=opening?to:from,clone=poster.cloneNode(true);clone.className='flightPoster';Object.assign(clone.style,{left:box.left+'px',top:box.top+'px',width:box.width+'px',height:box.height+'px'});document.body.append(clone);clone.animate([{left:box.left+'px',top:box.top+'px',width:box.width+'px',height:box.height+'px',borderRadius:'0px'},{left:dest.left+'px',top:dest.top+'px',width:dest.width+'px',height:dest.height+'px',borderRadius:i===2?'2px':'0px'}],{duration:opening?1050:760,easing:opening?'cubic-bezier(.76,0,.18,1)':'cubic-bezier(.55,0,.25,1)',fill:'forwards'}).finished.finally(()=>{clone.remove();done()})}
function openProject(i){if(transitionState!=='closed'&&active!==i)return;let cards=[...document.querySelectorAll('.card')],candidate=cards[i]?.querySelector('.poster');sourcePoster=candidate&&candidate.getBoundingClientRect().height?candidate:null;transitionState='opening';active=i;page=0;let p=data[i];mood(p);location.hash=p.slug;$('#home').style.cssText='opacity:0;transform:scale(.985)';$('#viewer').classList.add('active','entering');$('#viewer').classList.toggle('webMode',i===2);$('#closeBtn').style.display='block';$('#status').innerHTML=`<span>${p.no} / 04</span><span>${p.title}</span>`;$('.viewerBg').style.backgroundImage=`url('${p.bg}')`;$('#info').innerHTML=`<h2>${p.title}</h2><dl><dt>YEAR</dt><dd>${p.year}</dd><dt>TYPE</dt><dd>${p.type}</dd><dt>ROLE</dt><dd>${p.role}</dd><dt>TOOLS</dt><dd>${p.tools}</dd></dl><p>${p.desc}</p>`;draw();flyPoster(sourcePoster,i,true,()=>{$('#viewer').classList.remove('entering');transitionState='open'})}
function turn(dir){if(active<0||busy||transitionState!=='open')return;let p=data[active],len=p.pages.length;if(active===2){page=(page+(dir==='next'?1:-1)+len)%len;drawWeb();return}let mobile=innerWidth<=800,next;if(mobile)next=(page+(dir==='next'?1:-1)+len)%len;else if(dir==='next')next=page===0?1:(page+2>=len?0:page+2);else next=page===0?(len%2===0?len-1:len-2):(page===1?0:page-2);let old=$('#book').querySelector(dir==='next'?'.right':'.left'),leaf=old&&old.cloneNode(true);page=next;draw();if(leaf){busy=true;leaf.classList.add('turn');if(dir!=='next')leaf.classList.add('back');$('#book').append(leaf);setTimeout(()=>{leaf.remove();busy=false},880)}}
function finishClose(){active=-1;location.hash='home';$('#viewer').classList.remove('active','webMode','leaving');$('#info').classList.remove('active');$('#home').style.cssText='';$('#closeBtn').style.display='none';$('#status').innerHTML='<span>SELECTED WORKS</span><span>2024—2026</span>';transitionState='closed'}
function close(){if(active<0||transitionState==='closing')return;transitionState='closing';let i=active,poster=sourcePoster&&document.contains(sourcePoster)?sourcePoster:null;$('#viewer').classList.add('leaving');flyPoster(poster,i,false,finishClose)}
document.querySelectorAll('.card').forEach((card,i)=>{card.style.setProperty('--reveal-delay',`${i*.06}s`)});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('revealed')}),{threshold:.16});document.querySelectorAll('.card').forEach(x=>revealObserver.observe(x));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&innerWidth>800){let ticking=false;addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{document.querySelectorAll('.card.revealed').forEach(card=>{let r=card.getBoundingClientRect(),shift=Math.max(-14,Math.min(14,(r.top+r.height/2-innerHeight/2)*-.025));card.style.setProperty('--parallax',shift+'px')});ticking=false})},{passive:true})}
if(initial>=0)openProject(initial);
