const $=s=>document.querySelector(s), reduced=matchMedia('(prefers-reduced-motion: reduce)');
const projects=[
{slug:'rebuild',no:'01',title:'REBUILD',type:'VISUAL RESEARCH',year:'2024',format:'HARDCOVER / A3',color:'#454c4c',accent:'#c5c8be',paper:'#d5d4ce',depth:.22,rough:.83,cover:'assets/rebuild-poster.webp',pages:['assets/rebuild-poster.webp','assets/rebuild-collapse.webp','assets/rebuild-structure.webp','assets/rebuild-construction.webp'],desc:'Unfinished structures. Traces of expansion. A photographic study of Kunming, between construction and reconstruction.',role:'Concept, Art Direction, Editorial Design',tools:'Photoshop, Lightroom'},
{slug:'yunnan-fungal-diversity',no:'02',title:'YUNNAN FUNGAL DIVERSITY',type:'FIELD EDITORIAL',year:'2025',format:'SOFTCOVER / A3',color:'#47443a',accent:'#edc35d',paper:'#e0ded1',depth:.085,rough:.48,cover:'assets/fungi-cover.webp',pages:['assets/fungi-cover.webp','assets/golden-ear.webp','assets/gongshan-mist.webp','assets/gongshan-portrait.webp','assets/gongshan-rock.webp'],desc:'From a golden fungus to a wider ecology. Field images from Gongshan, Yunnan, translated into the visual language of a science publication.',role:'Art Direction, Editorial Design',tools:'Photoshop, Lightroom'},
{slug:'the-breath-of-indigo',no:'03',title:'THE BREATH OF INDIGO',type:'INTERACTIVE EXPERIENCE',year:'2026',format:'DIGITAL / WEB EXPERIENCE',color:'#183b55',accent:'#8eaecd',paper:'#1b3048',depth:.07,rough:.3,cover:'assets/indigo-hero.webp',pages:['assets/indigo-hero.webp','assets/indigo-craft.webp','assets/indigo-workshop.webp'],desc:'A digital exploration of Dali tie-dye. Pattern, process and place come together through an interface shaped by indigo.',role:'Concept, UI Design, Interaction Design',tools:'Base44, Claude, Dreamweaver'},
{slug:'shape-of-love',no:'04',title:'SHAPE OF LOVE',type:'PERSONAL EDITORIAL',year:'2025',format:'PHOTOBOOK / A3',color:'#665c5d',accent:'#e5bfc1',paper:'#eee1d6',depth:.17,rough:.57,cover:'assets/love-birthday.webp',pages:['assets/love-birthday.webp','assets/love-portrait-1.webp','assets/love-portrait-2.webp','assets/love-portrait-3.webp','assets/love-throw.webp'],desc:'A birthday, a portrait, a small collection of affection. Images composed into a personal edition about growing up.',role:'Art Direction, Editorial Design',tools:'Photoshop'}];
const mobile=()=>innerWidth<=800;
const lerp=(a,b,t)=>a+(b-a)*t, clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v)), ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
let active=null,mode='home',page=0,transition=null,leafTween=null,drag=null,returnFocus=null,webIndex=0;
let models=[],THREE,renderer,clock=0,visibleSlots=new Set(),loaded=0;
const images=new Map(),textures=new Map(),failed=[];
projects.forEach((p,i)=>{$('#projectList').insertAdjacentHTML('beforeend',`<article class="edition" id="edition-${p.slug}" data-no="${p.no}" style="--accent:${p.accent}"><button class="objectSlot" data-project="${i}" aria-label="Open ${p.title}"><img class="fallback" src="${p.cover}" alt="${p.title} poster" loading="lazy"></button><div class="editionCopy"><div class="editionNumber"><span>EDITION ${p.no} / 04</span><span>${p.year}</span></div><h2>${p.title}</h2><p>${p.desc}</p><dl><dt>DISCIPLINE</dt><dd>${p.type}</dd><dt>FORMAT</dt><dd>${p.format}</dd></dl><button class="enterEdition" data-project="${i}">EXPLORE EDITION <span>↗</span></button></div></article>`)});
const slots=[...document.querySelectorAll('.objectSlot')];
function mood(i){$('#environment').style.backgroundColor=projects[i].color;document.documentElement.style.setProperty('--accent',projects[i].accent)}
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){visibleSlots.add(e.target);e.target.closest('.edition')?.classList.add('visible');if(mode==='home')mood(+e.target.dataset.project)}else visibleSlots.delete(e.target)}},{threshold:.15});slots.forEach(s=>observer.observe(s));
function notice(message){$('#notice').textContent=message;$('#notice').hidden=false}
function loadImage(src){if(images.has(src))return Promise.resolve(images.get(src));return new Promise(resolve=>{const im=new Image();im.onload=()=>{images.set(src,im);resolve(im)};im.onerror=()=>{failed.push(src);resolve(null)};im.src=src})}
// A3 art textures: only the translucent background copy is cropped. The original is contained.
function artTexture(src,ratio=297/420){const key=src+ratio;if(textures.has(key))return textures.get(key);const im=images.get(src);const c=document.createElement('canvas');c.height=1536;c.width=Math.round(c.height*ratio);const g=c.getContext('2d');g.fillStyle='#dedbd4';g.fillRect(0,0,c.width,c.height);if(im){const cover=Math.max(c.width/im.width,c.height/im.height);g.save();g.globalAlpha=.18;g.filter='blur(32px)';g.drawImage(im,(c.width-im.width*cover)/2,(c.height-im.height*cover)/2,im.width*cover,im.height*cover);g.restore();const contain=Math.min(c.width/im.width,c.height/im.height);g.drawImage(im,(c.width-im.width*contain)/2,(c.height-im.height*contain)/2,im.width*contain,im.height*contain)}else{g.fillStyle='#343638';g.font='32px sans-serif';g.fillText('Image unavailable',60,c.height/2)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures.set(key,t);return t}
function paperTexture(p){const c=document.createElement('canvas');c.width=64;c.height=512;const g=c.getContext('2d');g.fillStyle=p.paper;g.fillRect(0,0,64,512);for(let y=0;y<512;y+=4){g.fillStyle=y%12?'#00000012':'#00000028';g.fillRect(0,y,64,1)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const W=2.828,H=4;
function material(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.75,...extra})}
function box(w,h,d,mat,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m}
function artPlane(src,w=W,h=H,side=THREE.FrontSide){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h,8,12),material('#ffffff',{map:artTexture(src,w/h),side,roughness:.88}));m.material.userData.layer=2;m.castShadow=true;m.receiveShadow=true;return m}
class EditionModel{
 constructor(slot){this.slot=slot;this.i=+slot.dataset.project;this.p=projects[this.i];this.web=this.i===2;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(35,1,.1,50);this.camera.position.set(0,0,9);this.root=new THREE.Group();this.scene.add(this.root);this.body=new THREE.Group();this.root.add(this.body);this.openAmount=0;this.spread=0;this.pointer={x:0,y:0};this.rotation={x:0,y:0,z:0};this.scene.add(new THREE.AmbientLight('#ffffff',1.7));const key=new THREE.DirectionalLight('#fff8ec',2.1);key.position.set(-3,6,9);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.bias=-.0005;key.shadow.normalBias=.015;this.scene.add(key);const rim=new THREE.DirectionalLight('#cad9e9',.6);rim.position.set(5,-1,4);this.scene.add(rim);const shade=new THREE.Mesh(new THREE.PlaneGeometry(16,14),new THREE.ShadowMaterial({opacity:.23}));shade.position.z=-.6;shade.receiveShadow=true;this.scene.add(shade);this.build();slot.addEventListener('pointermove',e=>{const r=slot.getBoundingClientRect();this.pointer={x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5}});slot.addEventListener('pointerleave',()=>this.pointer={x:0,y:0});}
 build(){const p=this.p,d=p.depth;this.width=this.web?4.5:W;this.height=this.web?3.05:H;const w=this.width,h=this.height;
 const edge=material(p.paper,{map:paperTexture(p),roughness:.96});const binding=material(this.web?'#13263a':p.color,{roughness:p.rough});
 this.rightBlock=box(w-.06,h-.05,d,edge,w/2,0,-d/2);this.body.add(this.rightBlock);this.back=box(w+.025,h+.025,.035,binding,w/2,0,-d-.015);this.body.add(this.back);
 this.spine=box(.065,h+.025,d+.065,binding,.015,0,-d/2);this.body.add(this.spine);
 this.coverPivot=new THREE.Group();this.body.add(this.coverPivot);const cover=box(w+.025,h+.025,.03,binding,w/2,0,.032);this.coverPivot.add(cover);this.coverArt=artPlane(p.cover,w,h);this.coverArt.position.set(w/2,0,.05);this.coverPivot.add(this.coverArt);const inside=artPlane(p.cover,w,h,THREE.BackSide);inside.position.set(w/2,0,.014);this.coverPivot.add(inside);
 this.leftBlock=box(w-.055,h-.05,d*.7,edge,-w/2,0,-d*.5);this.body.add(this.leftBlock);this.leftBack=box(w+.025,h+.025,.035,binding,-w/2,0,-d-.015);this.body.add(this.leftBack);
 this.left=artPlane(p.pages[1]||p.cover,w,h);this.left.position.set(-w/2,0,.018);this.body.add(this.left);this.right=artPlane(p.pages[2]||p.cover,w,h);this.right.position.set(w/2,0,.018);this.body.add(this.right);
 // Two separately textured faces share the physically curved page surface.
 this.leaf=new THREE.Group();this.body.add(this.leaf);this.leafFront=new THREE.Mesh(new THREE.PlaneGeometry(w,h,48,6),material('#ffffff',{side:THREE.FrontSide}));this.leafBack=new THREE.Mesh(new THREE.PlaneGeometry(w,h,48,6),material('#ffffff',{side:THREE.BackSide}));this.leafFront.material.userData.layer=this.leafBack.material.userData.layer=4;this.coverArt.material.userData.layer=3;inside.material.userData.layer=3;this.leafFront.castShadow=this.leafFront.receiveShadow=this.leafBack.castShadow=this.leafBack.receiveShadow=true;this.leaf.add(this.leafFront,this.leafBack);const uv=this.leafBack.geometry.attributes.uv;for(let j=0;j<uv.count;j++)uv.setX(j,1-uv.getX(j));this.leaf.visible=false;this.setOpen(0);
 }
 setOpen(v){this.openAmount=v;this.body.position.x=-this.width/2*(1-v);this.coverPivot.rotation.y=-Math.PI*v;this.coverPivot.visible=v<.999;this.left.visible=this.leftBlock.visible=this.leftBack.visible=v>.01&&!mobile();this.leftBlock.scale.x=Math.max(.001,v);this.leftBack.scale.x=Math.max(.001,v);this.right.visible=v>.8;this.spine.visible=v<.9;if(mobile()&&v>.99)this.body.position.x=-this.width/2;}
 setPages(start){this.spread=start;const p=this.p,indices=currentIndices(start,p);this.left.material.map=artTexture(p.pages[indices[0]],this.width/this.height);this.right.material.map=artTexture(p.pages[indices.at(-1)],this.width/this.height);this.left.material.needsUpdate=this.right.material.needsUpdate=true;}
 beginLeaf(dir,next){this.leaf.visible=true;this.direction=dir;const old=currentIndices(page,this.p),fresh=currentIndices(next,this.p);this.leafFront.material.map=artTexture(this.p.pages[dir>0?old.at(-1):fresh.at(-1)]);this.leafBack.material.map=artTexture(this.p.pages[dir>0?fresh[0]:old[0]]);this.leafFront.material.needsUpdate=this.leafBack.material.needsUpdate=true;if(dir>0)this.right.material.map=artTexture(this.p.pages[fresh.at(-1)]);else this.left.material.map=artTexture(this.p.pages[fresh[0]]);this.bend(dir>0?0:1)}
 bend(t){const w=this.width,h=this.height,segments=48;const xz=[[0,.05]];for(let k=1;k<=segments;k++){const u=(k-.5)/segments;const angle=Math.PI*t+Math.sin(Math.PI*t)*.95*(u-.45);xz.push([xz[k-1][0]+Math.cos(angle)*w/segments,xz[k-1][1]+Math.sin(angle)*w/segments])}for(const mesh of [this.leafFront,this.leafBack]){const pos=mesh.geometry.attributes.position;for(let k=0;k<pos.count;k++){const col=k%(segments+1),row=Math.floor(k/(segments+1)),u=col/segments,y=h/2-row*h/6;pos.setXYZ(k,xz[col][0],y,xz[col][1]+Math.sin(Math.PI*t)*.08*u*u*(y/h))}pos.needsUpdate=true;mesh.geometry.computeVertexNormals()}}
 idle(t){const phase=t*.45+this.i*1.7;const rx=.10+Math.sin(phase*.75)*.052+this.pointer.y*.06,ry=-.32+Math.sin(phase)*.14+this.pointer.x*.1,rz=.025+Math.sin(phase*.6)*.018;this.root.rotation.set(reduced.matches?.06:rx,reduced.matches?-.32:ry,reduced.matches?0:rz);this.root.position.y=reduced.matches?0:Math.sin(phase*.8)*.055;this.rotation={x:this.root.rotation.x,y:this.root.rotation.y,z:this.root.rotation.z};}
 render(rect,reading=false){if(rect.width<1||rect.height<1)return;const aspect=rect.width/rect.height;this.camera.aspect=aspect;const open=reading?this.openAmount:0;const modelW=this.width*(mobile()?1:1+open);const visibleH=Math.max(this.height*1.2,modelW/aspect*1.14);this.camera.position.z=visibleH/(2*Math.tan(35*Math.PI/360));this.camera.updateProjectionMatrix();renderer.setViewport(rect.left,innerHeight-rect.bottom,rect.width,rect.height);const l=Math.max(0,rect.left),b=Math.max(0,innerHeight-rect.bottom),r=Math.min(innerWidth,rect.right),top=Math.min(innerHeight,innerHeight-rect.top);renderer.setScissor(l,b,Math.max(0,r-l),Math.max(0,top-b));renderer.render(this.scene,this.camera);}
}
function currentIndices(n,p){if(n===0)return[0];if(mobile())return[n];return[n,(n+1)%p.pages.length]}
function nextPage(dir){const len=active.p.pages.length;if(mobile())return(page+dir+len)%len;if(dir>0)return page===0?1:page+2>=len?0:page+2;return page===0?(len%2===0?len-1:len-2):page===1?0:page-2}
function boxRect(r){return {left:r.left,top:r.top,width:r.width,height:r.height,right:r.right,bottom:r.bottom}}
function mixRect(a,b,t){const left=lerp(a.left,b.left,t),top=lerp(a.top,b.top,t),width=lerp(a.width,b.width,t),height=lerp(a.height,b.height,t);return{left,top,width,height,right:left+width,bottom:top+height}}
function targetRect(){return boxRect($('#readerStage').getBoundingClientRect())}
function count(){const ids=currentIndices(page,active.p);$('#pageCount').textContent=page===0?'COVER':ids.map(n=>String(n+1).padStart(2,'0')).join(' — ')+' / '+String(active.p.pages.length).padStart(2,'0');$('#readerStage').dataset.pages=ids.join(',');$('#readerStage').dataset.project=active.p.slug;$('#readerStage').dataset.mode=page?'spread':'cover'}
function openProject(i,slot){if(mode!=='home')return;returnFocus=document.activeElement;active=models.find(m=>m.slot===slot)||models.find(m=>m.i===i);if(!active){notice('3D is unavailable on this device. Showing the complete original images.');openFallback(i);return}page=0;active.setOpen(0);mood(i);$('#reader').hidden=false;$('#closeBtn').hidden=false;$('#home').inert=true;$('#status').textContent=`${projects[i].no} / 04 — ${projects[i].title}`;const from=boxRect(active.slot.getBoundingClientRect());mode='opening';transition={from,to:targetRect(),start:performance.now(),duration:reduced.matches?0:1150,rotation:{...active.rotation}};document.body.classList.add('reading');history.replaceState(null,'','#'+projects[i].slug);$('#next').focus();count()}
function openFallback(i){active={i,p:projects[i],fallback:true};mode='reading';page=0;$('#reader').hidden=false;$('#closeBtn').hidden=false;$('#home').inert=true;document.body.classList.add('reading');$('#webReader').hidden=false;$('#readerStage').hidden=true;$('#webReader').innerHTML=projects[i].pages.map((src,j)=>`<figure class="webSection"><img src="${src}" alt="${projects[i].title} image ${j+1}"></figure>`).join('');$('#zoomBtn').hidden=true;$('#pageCount').textContent='SCROLL TO EXPLORE';}
function showWeb(){const p=active.p;$('#webReader').innerHTML=`<div class="browserBar">○ ○ ○ <span>the-breath-of-indigo</span></div><nav class="webTabs">${['OVERVIEW','EXPERIENCE','INTERACTION'].map((s,i)=>`<button data-section="${i}">${s}</button>`).join('')}</nav>${p.pages.map((src,i)=>`<figure class="webSection" id="web-${i}"><img src="${src}" alt="${p.title} — ${['overview','experience','interaction'][i]}"><figcaption>0${i+1} / ${['OVERVIEW','EXPERIENCE','INTERACTION'][i]}</figcaption></figure>`).join('')}`;$('#webReader').hidden=false;$('#webReader').scrollTop=0;$('#readerStage').hidden=true;$('.gestureHint').textContent='SCROLL WITHIN THE WEB EXPERIENCE';$('#pageCount').textContent='WEB EXPERIENCE';$('#zoomBtn').hidden=true;$('#webReader').querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>webGo(+b.dataset.section));$('#webReader').animate([{opacity:0,transform:'perspective(1400px) rotateY(-8deg)'},{opacity:1,transform:'none'}],{duration:reduced.matches?0:600,easing:'ease-out'});}
function webGo(i){webIndex=(i+3)%3;$('#web-'+webIndex)?.scrollIntoView({behavior:reduced.matches?'auto':'smooth',block:'start'})}
function closeProject(){if(!active||mode==='closing'||transition||leafTween||drag)return;for(const d of document.querySelectorAll('dialog[open]'))d.close();if(active.fallback){finishClose();return}if(active.web){$('#webReader').hidden=true;$('#readerStage').hidden=false}mode='closing';const begin=()=>{transition={from:targetRect(),to:boxRect(active.slot.getBoundingClientRect()),start:performance.now(),duration:reduced.matches?0:1000,rotation:{...active.rotation}}};if(active.openAmount>0){leafTween={kind:'close',from:active.openAmount,to:0,start:performance.now(),duration:reduced.matches?0:700,done:begin}}else begin()}
function finishClose(){active?.setOpen?.(0);active=null;mode='home';transition=null;page=0;$('#reader').hidden=true;$('#webReader').hidden=true;$('#readerStage').hidden=false;$('#zoomBtn').hidden=false;$('#closeBtn').hidden=true;$('#home').inert=false;document.body.classList.remove('reading');$('#status').textContent='INDEPENDENT VISUAL EDITIONS';$('.gestureHint').textContent='DRAG A PAGE EDGE · ARROW KEYS TO TURN';history.replaceState(null,'','#home');returnFocus?.focus({preventScroll:true})}
function coverMotion(open,done){leafTween={kind:'cover',from:active.openAmount,to:open?1:0,start:performance.now(),duration:reduced.matches?0:1000,done}}
function turn(dir){if(!active||mode!=='reading'||transition||leafTween||drag)return;if(active.web){webGo(webIndex+dir);return}if(active.fallback)return;const n=nextPage(dir);if(page===0){active.setPages(n);coverMotion(true,()=>{page=n;count()});return}if(n===0){coverMotion(false,()=>{page=0;count()});return}active.beginLeaf(dir,n);leafTween={kind:'leaf',from:dir>0?0:1,to:dir>0?1:0,start:performance.now(),duration:reduced.matches?0:1050,done:()=>{page=n;active.setPages(page);active.leaf.visible=false;count()}}}
function enlarge(){if(!active)return;const ids=currentIndices(page,active.p);$('#lightboxImages').innerHTML=ids.map(n=>`<img src="${active.p.pages[n]}" alt="${active.p.title} — image ${n+1}">`).join('');$('#lightbox').showModal()}
function openIndex(){const p=active?.p;$('#catalogTitle').textContent=p?`${p.title} / PAGE INDEX`:'EDITION INDEX';$('#catalogGrid').innerHTML=p?p.pages.map((s,i)=>`<button class="catalogItem" data-page="${i}"><img src="${s}" alt="${p.title} image ${i+1}"><span>${String(i+1).padStart(2,'0')} / ${i===0?'COVER':'IMAGE'}</span></button>`).join(''):projects.map((q,i)=>`<button class="catalogItem" data-open="${i}"><img src="${q.cover}" alt="${q.title} poster"><span>${q.no} / ${q.title}</span></button>`).join('');$('#catalog').showModal();$('#catalogGrid').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const i=+b.dataset.open;$('#catalog').close();const slot=slots.find(s=>+s.dataset.project===i&&!s.classList.contains('heroObject'));slot.scrollIntoView({block:'center',behavior:'instant'});openProject(i,slot)});$('#catalogGrid').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(mode!=='reading'||leafTween||drag)return;$('#catalog').close();const n=+b.dataset.page;if(active.web){webGo(n);return}if(active.fallback)return;page=n===0?0:mobile()?n:n%2?n:n-1;active.setPages(page);active.setOpen(page?1:0);count()})}
function openInfo(){const p=active?.p;$('#infoContent').innerHTML=p?`<h2>${p.title}</h2><dl><dt>EDITION</dt><dd>${p.no} / 04</dd><dt>YEAR</dt><dd>${p.year}</dd><dt>FORMAT</dt><dd>${p.format}</dd><dt>ROLE</dt><dd>${p.role}</dd><dt>TOOLS</dt><dd>${p.tools}</dd></dl><p>${p.desc}</p>`:'<h2>WED<br>Visual Editions.</h2><p>A selection of photography, editorial design and digital experiences by WED.</p><dl><dt>PERIOD</dt><dd>2024—2026</dd><dt>EDITIONS</dt><dd>04</dd></dl>';$('#information').showModal()}
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(+b.dataset.project,b.classList.contains('objectSlot')?b:b.closest('.edition').querySelector('.objectSlot')));
$('#next').onclick=()=>turn(1);$('#previous').onclick=()=>turn(-1);$('#closeBtn').onclick=closeProject;$('#zoomBtn').onclick=enlarge;$('#indexBtn').onclick=openIndex;$('#infoBtn').onclick=openInfo;
document.querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=()=>$('#'+b.dataset.dismiss).close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
$('.wordmark').onclick=e=>{if(active){e.preventDefault();closeProject()}};
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape')closeProject();if(e.key==='ArrowRight')turn(1);if(e.key==='ArrowLeft')turn(-1);if(e.key==='Tab'&&active){const focusable=[...document.querySelectorAll('header button:not([hidden]),#reader button:not([hidden])')].filter(b=>b.offsetParent!==null);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const stage=$('#readerStage');stage.addEventListener('pointerdown',e=>{if(mode!=='reading'||!active||active.web||active.fallback||leafTween)return;const r=stage.getBoundingClientRect(),relative=(e.clientX-r.left)/r.width;const dir=relative>.5?1:-1;drag={x:e.clientX,y:e.clientY,dir,start:performance.now(),progress:0,next:nextPage(dir),leaf:false,moved:false};stage.setPointerCapture(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(!drag)return;const dx=(drag.x-e.clientX)*drag.dir,dy=Math.abs(e.clientY-drag.y);if(Math.abs(dx)>7||dy>10)drag.moved=true;drag.progress=clamp(dx/(stage.clientWidth*(mobile()?.65:.42)));if(page>0&&drag.next>0&&!reduced.matches){if(!drag.leaf){active.beginLeaf(drag.dir,drag.next);drag.leaf=true}active.bend(drag.dir>0?drag.progress:1-drag.progress)}});
function release(cancel=false){if(!drag)return;const d=drag;drag=null;if(cancel&&d.leaf){active.leaf.visible=false;active.setPages(page);return}if(d.leaf){const complete=!cancel&&(d.progress>.32||(d.progress>.1&&performance.now()-d.start<250));leafTween={kind:'leaf',from:d.dir>0?d.progress:1-d.progress,to:d.dir>0?(complete?1:0):(complete?0:1),start:performance.now(),duration:reduced.matches?0:Math.max(300,800*(complete?1-d.progress:d.progress)),done:()=>{if(complete)page=d.next;active.setPages(page);active.leaf.visible=false;count()}}}else if(!cancel&&(!d.moved||d.progress>.15))turn(d.dir)}
stage.addEventListener('pointerup',()=>release());stage.addEventListener('pointercancel',()=>release(true));stage.addEventListener('dblclick',enlarge);
function frame(now){requestAnimationFrame(frame);if(!renderer||document.hidden)return;clock=now/1000;renderer.setScissorTest(false);renderer.clear();renderer.setScissorTest(true);
 if(leafTween&&active){const a=leafTween,t=clamp((now-a.start)/(a.duration||1)),v=lerp(a.from,a.to,ease(t));if(a.kind==='leaf')active.bend(v);else active.setOpen(v);if(t===1){leafTween=null;a.done?.()}}
 if(transition&&active){const a=transition,t=clamp((now-a.start)/(a.duration||1)),e=ease(t);const opening=mode==='opening';active.root.rotation.set(lerp(opening?a.rotation.x:.025,opening?.025:a.rotation.x,e),lerp(opening?a.rotation.y:0,opening?0:a.rotation.y,e),lerp(opening?a.rotation.z:0,opening?0:a.rotation.z,e));active.root.position.y=0;active.render(mixRect(a.from,a.to,e),true);if(t===1){transition=null;if(opening){mode='reading';if(active.web)showWeb();else{const n=1;active.setPages(n);coverMotion(true,()=>{page=n;count()})}}else finishClose()}}
 else if(active){if(!active.fallback&&(!active.web||mode==='closing')){active.root.rotation.set(.025,0,0);active.root.position.y=0;active.render(targetRect(),true)}}
 else{for(const m of models){if(!visibleSlots.has(m.slot))continue;const r=boxRect(m.slot.getBoundingClientRect());if(r.bottom<0||r.top>innerHeight)continue;m.idle(clock);const drift=reduced.matches?0:clamp((r.top+r.height/2-innerHeight/2)*-.025,-16,16);r.top+=drift;r.bottom+=drift;m.render(r)}}
}
function resize(){renderer?.setPixelRatio(Math.min(devicePixelRatio,mobile()?1.5:2));renderer?.setSize(innerWidth,innerHeight,false);if(drag)release(true);if(active&&!active.web&&!active.fallback){if(page>0&&!mobile()&&page%2===0)page=Math.max(1,page-1);active.setPages(page);active.setOpen(page?1:0);count()}}
addEventListener('resize',resize);
async function boot(){try{THREE=await import('./three.module.min.js');try{renderer=new THREE.WebGLRenderer({canvas:$('#world'),alpha:true,antialias:true})}catch(error){const old=$('#world'),replacement=old.cloneNode();old.replaceWith(replacement);const {SoftwareRenderer}=await import('./software-renderer.js?v=20260916-7d');renderer=new SoftwareRenderer(THREE,replacement)}renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;resize();const all=[...new Set(projects.flatMap(p=>p.pages))];await Promise.all(all.map(async src=>{await loadImage(src);$('#loading progress').value=++loaded/all.length}));models=slots.map(s=>new EditionModel(s));document.body.classList.add('gpu-ready');document.body.dataset.renderer=renderer.software?'software-3d':'webgl';$('#loading').hidden=true;if(failed.length)notice(`${failed.length} image(s) could not load. Refresh to retry.`);requestAnimationFrame(frame);const start=projects.findIndex(p=>p.slug===location.hash.slice(1));if(start>=0)openProject(start,slots.find(s=>+s.dataset.project===start));$('#world').addEventListener('webglcontextlost',e=>{e.preventDefault();notice('The 3D view was interrupted. Refresh to restore it.');document.body.classList.remove('gpu-ready')});}catch(error){console.error(error);$('#loading').hidden=true;notice('3D is unavailable. Select a poster to view all original images.')}}
boot();
